//! Spec-mode synthesis pass — roadmap item #28.
//!
//! Looks for fns with `#[spec(intent="…")]`. For each one:
//!   1. If a sibling `<src_dir>/<fn_name>.spec.aether` file exists, parse
//!      it as an impl body and splice it into the fn — replacing whatever
//!      stub body the source has (typically empty `{}`).
//!   2. Otherwise, write a `<src_dir>/<fn_name>.spec` request file that
//!      records the intent + signature + a hint about where to drop the
//!      synthesised body. The fn's existing body stays as-is (stub).
//!
//! This is the **human-gated** form the roadmap calls for: the user (or a
//! downstream LLM tool) reads the .spec request, writes the corresponding
//! .spec.aether body file, and re-runs aetherc — the next compile picks
//! up the impl. No LLM is called from inside aetherc; the gate is mech-
//! anical (file existence) so it stays auditable.
//!
//! Once a `claude` / API client wires in, replace the "write request +
//! warn" branch with "synthesise + write body + warn-with-diff".

use std::path::Path;
use crate::ast::{Block, Expr, FnDecl, Item, Param, Program, Ty};
use crate::lexer::Lexer;
use crate::parser::Parser;

/// Returns `(synthesised_count, missing_count)`.
pub fn run(prog: &mut Program, src_dir: Option<&Path>) -> (usize, usize) {
    let mut synth = 0usize;
    let mut miss  = 0usize;
    let src_dir = match src_dir { Some(d) => d, None => return (0, 0) };
    let mut new_items: Vec<Item> = Vec::with_capacity(prog.items.len());
    for item in std::mem::take(&mut prog.items) {
        match item {
            Item::Fn(mut f) => {
                if let Some(intent) = spec_intent(&f) {
                    let body_file = src_dir.join(format!("{}.spec.aether", f.name));
                    if body_file.exists() {
                        match load_body(&body_file, &f) {
                            Ok(b) => { f.body = Some(b); synth += 1; }
                            Err(e) => {
                                eprintln!("[aetherc spec] {} body file present but failed to parse: {}",
                                    f.name, e);
                                miss += 1;
                            }
                        }
                    } else {
                        let req = src_dir.join(format!("{}.spec", f.name));
                        let _ = std::fs::write(&req,
                            format!("# spec request — auto-generated by aetherc\n\
                                     # intent: {}\n\
                                     # signature: {}\n\
                                     # to satisfy: drop the body source into\n\
                                     #   {}\n\
                                     # then re-run aetherc.\n",
                                intent, render_sig(&f),
                                src_dir.join(format!("{}.spec.aether", f.name)).display()));
                        eprintln!("[aetherc spec] missing impl for `{}` — wrote request to {}",
                            f.name, req.display());
                        miss += 1;
                    }
                }
                new_items.push(Item::Fn(f));
            }
            other => new_items.push(other),
        }
    }
    prog.items = new_items;
    (synth, miss)
}

fn spec_intent(f: &FnDecl) -> Option<&str> {
    f.attrs.iter().find(|a| a.name == "spec").and_then(|a| a.arg_str("intent"))
}

fn render_sig(f: &FnDecl) -> String {
    let params: Vec<String> = f.params.iter().map(|p|
        format!("{}: {}", p.name, render_ty(&p.ty))).collect();
    let ret = f.ret.as_ref().map(|t| format!(" -> {}", render_ty(t))).unwrap_or_default();
    format!("fn {}({}){}", f.name, params.join(", "), ret)
}

fn render_ty(t: &Ty) -> String {
    match t {
        Ty::Named(n) => n.clone(),
        Ty::Ref { mutable, inner } =>
            format!("&{}{}", if *mutable { "mut " } else { "" }, render_ty(inner)),
        Ty::Generic { name, args } => {
            let a: Vec<String> = args.iter().map(render_ty).collect();
            format!("{}<{}>", name, a.join(", "))
        }
        Ty::Shape(_) => "<shape>".into(),
        Ty::Array { elem, n } => format!("[{}; {}]", render_ty(elem), n),
        Ty::Tuple(ts) => {
            let s: Vec<String> = ts.iter().map(render_ty).collect();
            format!("({})", s.join(", "))
        }
        Ty::Unit => "()".into(),
    }
}

/// Parse the spec body file as a fragment containing exactly one fn whose
/// name + signature match the original. Splice the fn's body into the
/// caller. Lets the synthesis target be a self-contained, lex+parse-able
/// .aether snippet.
fn load_body(body_file: &Path, original: &FnDecl) -> Result<Block, String> {
    let src = std::fs::read_to_string(body_file)
        .map_err(|e| format!("read {:?}: {}", body_file, e))?;
    let (toks, _) = Lexer::new(&src).tokenize().map_err(|e| format!("lex: {}", e))?;
    let mut prog = Parser::new(toks).parse_program()
        .map_err(|e| format!("parse: {}", e))?;
    for item in prog.items.drain(..) {
        if let Item::Fn(f) = item {
            if f.name == original.name {
                if !sig_matches(&f, original) {
                    return Err(format!("signature mismatch (file declares different params/ret for {})", f.name));
                }
                return f.body.ok_or_else(|| format!("body file's fn `{}` has no body", f.name));
            }
        }
    }
    Err(format!("no fn `{}` in body file", original.name))
}

fn sig_matches(a: &FnDecl, b: &FnDecl) -> bool {
    if a.params.len() != b.params.len() { return false; }
    a.params.iter().zip(b.params.iter()).all(|(p, q)| p.name == q.name && tys_eq(&p.ty, &q.ty))
        && rets_eq(&a.ret, &b.ret)
}

fn tys_eq(a: &Ty, b: &Ty) -> bool {
    match (a, b) {
        (Ty::Named(x), Ty::Named(y)) => x == y,
        (Ty::Unit, Ty::Unit) => true,
        (Ty::Ref { mutable: m1, inner: i1 }, Ty::Ref { mutable: m2, inner: i2 }) =>
            m1 == m2 && tys_eq(i1, i2),
        _ => render_ty(a) == render_ty(b),  // pragma: cheap fallback
    }
}

fn rets_eq(a: &Option<Ty>, b: &Option<Ty>) -> bool {
    match (a, b) {
        (None, None) => true,
        (Some(x), Some(y)) => tys_eq(x, y),
        _ => false,
    }
}

/// Treat a body as "stub" if it's empty `{}` or just `{ 0 }` etc.
/// (Currently unused — the pass replaces the body unconditionally when
/// the .spec.aether file exists. Provided for future "warn on overwrite"
/// behaviour once we want to refuse to clobber a hand-written body.)
#[allow(dead_code)]
fn body_looks_stub(b: &Block) -> bool {
    b.stmts.is_empty() && match &b.tail {
        None => true,
        Some(e) => matches!(e.as_ref(), Expr::IntLit(0)),
    }
}

/// (Unused today — sketch of the future synthesis-time helper.)
#[allow(dead_code)]
fn _scaffold_param_unused(_: &Param) {}
